replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.6.0
  pullPolicy: IfNotPresent

auth:
  enabled: false

zookeeper:
  enabled: true
  replicaCount: 1

persistence:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
