metrics:
  enabled: true

auth:
  existingSecret: my-db-secret
  secretKeys:
    postgresPasswordKey: postgres-password
  username: postgres
  database: ordersb

primary:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

metrics:
  enabled: true

image:
  repository: bitnami/postgresql
  tag: 15.6.0-debian-11-r5
