replicaCount: 1

service:
  type: NodePort
  port: 8080
  nodePort: 30081

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: order-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

image:
  repository: order-service
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: SPRING_DATASOURCE_URL
    valueFrom:
      configMapKeyRef:
        name: order-config
        key: SPRING_DATASOURCE_URL
  - name: SPRING_DATASOURCE_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: POSTGRES_USER
  - name: SPRING_DATASOURCE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: POSTGRES_PASSWORD
  - name: SPRING_SECURITY_PASSWORD
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: SPRING_SECURITY_PASSWORD
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: app-secrets
        key: JWT_SECRET