replicaCount: 1

image:
  repository: order-service
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 30081

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: order-service.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
# Example:
#   limits:
#     cpu: 200m
#     memory: 256Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/ordersb
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: password
  SPRING_SECURITY_PASSWORD: mysecureadminpass
  JWT_SECRET: joyo6iW6baFCaYL0r/+qwdCXe7t18lmxtyGHrMsEVP4=
