spring:
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:52432/ordersb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        format_sql: true

  security:
    user:
      name: admin
      password: your_secure_password

jwt:
  secret: joyo6iW6baFCaYL0r/+qwdCXe7t18lmxtyGHrMsEVP4=

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.yourcompany.orderservice.filter: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: health,info,env
