spring:
  application:
    name: order-service
  config:
    import: "configserver:http://config-server.default.svc.cluster.local:8888"
  profiles:
    active: prod
  cloud:
    config:
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
