apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
      name: kafka
  selector:
    app: {{ include "kafka.name" . }}
