apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
{{- range $env := .Values.env }}
            - name: {{ $env.name }}
{{- if $env.value }}
              value: {{ $env.value | quote }}
{{- end }}
{{- if $env.valueFrom }}
              valueFrom:
{{ toYaml $env.valueFrom | indent 16 }}
{{- end }}
{{- end }}

